### ISSUE TITLE
Interrupting leads to TypeError

### ISSUE THREAD

**Issue by winniederidder** [alexmojaki/python_runner#2]
After the recent changes including the handling of KeyboardInterrupt, I think interrupting no longer works properly.
I get a TypeError for catching classes that do not extend BaseException. After some exploring, I believe it has to do with the RuntimeErrors defined in PyodideRunner.
After some trial and error, the following code changes to PyodideRunner.sleep allows me to interrupt as expected:
```python
      except Exception as e:
          try:
              self.pyodide_error(e)
          except RuntimeError as re:
              if re in (self.ServiceWorkerError, self.NoChannelError):
                  pass
              raise
```

**Comment by alexmojaki** [comment]
oops, thanks for catching. released 0.5.1
